import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Dashboard.module.css'
import Button from '@/components/Counter'
import Link from 'next/link'
import Product from '@/components/Product'
import { useState } from 'react'
import { list } from '@/data/list'

const inter = Inter({ subsets: ['latin'] })

export default function Dashboard() {
    const [data, setData] = useState([...list.clothing])
    console.log(list);

  return (
    <>
      <Head>
        <title>Dashboard page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className={styles.main}>

        <p>
            <Link href="/">go to homepage</Link>
          </p> 
        <h2> Welcome, this is the dashboard page</h2>

        <h1>BCITSA Geared Up</h1>

        {
            data && data.map((i, index) => {
                return(
                    <div key={index}>
                      <Product img={i.image} tag={i.title} price={i.cost}/>
                      </div>
                )
            })
        }



      </div>
      </main>
    </>
  )
}
